### ISSUE TITLE
Contact wrench transformation question

### ISSUE THREAD

**Issue by stevenjj** [Tastalian/surface-contacts-icra-2015#2]
Hi Stephane, 
Thank you very much for providing the accompanying code to your paper.

I had a question on your contact wrench transformation, specifically in the following line:
https://github.com/stephane-caron/analytical-wrench-cone/blob/master/dmotions/hrp4/topp/wrench_cons.py#L187

My thought is that if my wrenches are defined in the world frame, then I need to use the Adjoint operator [1] to properly transform my world frame wrench to a local frame representation. The Adjoint operator would be a 6x6 transformation matrix that contains the rotation matrix R along the block diagonal, and an off-diagonal block matrix to account for local frame torques due to world frame linear forces. However, your implementation only contains the rotation matrix R along the diagonal.

For instance, I was expecting the transformation to be similar to the following pseudocode:
````
% F_a = [m_a, f_a] is a 6x1 vector representing the contact wrench in frame a (world), 
%    where m_a are moments about axes of frame a, and f_a are linear force vectors 
%    described in frame a.
% F_b = [m_b, f_b] is a 6x1 vector representing the contact wrench in frame b (local),
%    where m_b are moments about axes of frame b, and f_b are linear force vectors 
%    described in frame b.
% R is a 3x3 rotation matrix describing the orientation of frame b wr.t. to a
% p is 3x1 vector describing the linear offset from frame a to b.
% [p] is the 3x3 skew symmetric matrix of p. 

Adj_{a,b}(R,p) = [R, 0; [p]R, R] % The 6x6 Adjoint transformation matrix
F_b = Adj_{a,b}(R,p)^T * F_a % The resulting 6x1 local frame wrench representation
````

Am I misunderstanding your intended transformation? Otherwise what I am I missing? I would greatly appreciate your thoughts on this matter.

Thank you!

[1]  Lynch, Kevin M., and Frank C. Park. Modern Robotics. Cambridge University Press, 2017. pp. 110, equation 3.95. Available Online: [PDF](http://hades.mech.northwestern.edu/images/7/7f/MR.pdf)

**Comment by stephane-caron** [comment]
Hi Steven,

Exactly. In the code you point out, ``C_local`` applies to the body wrench, so the wrench friction cone is written as ``C_local * F_b <= 0``. Meanwhile, the wrench defined below (``C * wrench <= 0``) is expressed in the inertial frame located at the center of the rectangular foot contact area (hence ``p = 0``) with axes parallel to those of the world frame.

I've just added some comments on this to the code. Thank you for your feedback!

This is a convention I used for a while (as a matter of fact it is still around [in pymanoid](https://github.com/stephane-caron/pymanoid/blob/63140b3b1ccb99e77ce502f049630d5ce538a0c3/pymanoid/contact.py#L294)) but it's not the best one. It is actually easier to do everything with spatial vectors, so that you can readily convert your local wrench inequalities in the world frame as ``C_a * F_a <= 0`` with ``C_a = C_local * Adj_{a,b}(R,p)^T``. One way to interpret the Adjoint operator here is that the rows of the wrench inequality matrix are dual twists (see _e.g._ [Section III here](https://hal.archives-ouvertes.fr/hal-01349880/document)), which can come in handy when we want to consider them at a mobile point such as the center of mass.

Hoping this helps!

**Comment by stevenjj** [comment]
Hi Stephane, 

Thank you for the prompt response, clear explanation, and also for the linked paper. This very much helps! I now understand why `p = 0`, and why this results to a familiar wrench transformation. 

I only have one more follow-up question. With the given wrench description (i.e. defined with axes parallel to the world frame), I expected that the `wrench_rotation` matrix in the [same line](https://github.com/stephane-caron/analytical-wrench-cone/blob/49178f722e3dc8ee17ce9a57167ecd7a1214db9b/dmotions/hrp4/topp/wrench_cons.py#L194) to be defined as 
````
wrench_rotation = vstack([
    hstack([R.transpose(), O]),
    hstack([O, R.transpose()])])
````
where I assume that `R` is the rotation matrix of the link w.r.t. the world frame. With this definition for `R`, using the transpose (its inverse) makes more sense to me when viewing `R` simply as an operator that changes the reference frame in which the vector is represented. However, the transpose was not used in this case.

Additionally, I believe `R.transpose()` is actually used in [pymanoid](https://github.com/stephane-caron/pymanoid/blob/63140b3b1ccb99e77ce502f049630d5ce538a0c3/pymanoid/contact.py#L329). 

Is there an explanation for the discrepancy? 

Thank you again and my apologies for this very small detail. I'm in the process of using your CWC constraint and double checking our implementation with DART.

**Comment by stephane-caron** [comment]
Well there is a very clear explanation: you are right and this code is wrong :wink: 

I should have back-propagated the change from pymanoid, but obviously forgot. It's updated now, with a comment to the discussion here for details.

Thank you very much for checking this!

**Comment by stevenjj** [comment]
Hi Stephane,
Thank you for replying so quickly! This answers all of my questions.

I'm grateful once again that you made the code available which enabled me to study this particular implementation detail and helped with my understanding of the literature.

Thanks for the great work as always.
